### PR TITLE
Updated Cake.Core to 0.33.0

### PR DESCRIPTION
**Pull request by nils-a**
Also updated  Cake.Testing to 0.33.0 and the local cake version (for building) to 0.34.1

### CODE REVIEW

**Comment by nils-a** [comment]
also, this fixes #6

**Comment by nils-a** [comment]
Supersedes #7 and adresses half of #6

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@nils-a your changes have been merged, thanks for your contribution 👍

**Pull request merged**
