### PR TITLE
Switched the build to Cake.Recipe

### PR DESCRIPTION
**Pull request by nils-a**
and documentation generation from docfx to wyam.

### CODE REVIEW

**Comment by nils-a** [comment]
fixes #16

**Comment by gep13** [comment]
@nils-a are you in a position to rebase this, and fix up the conflicts, and then I can give it a review.

**Comment by nils-a** [comment]
@gep13 I rebased the changes. Hope it's not too unstructured to review 🙂

**Review by gep13 — APPROVED** [review]
LGTM

**Comment by gep13** [comment]
@nils-a thanks for getting this switched over!

**Pull request merged**
